system:
- changed-files:
  - any-glob-to-any-file: src/system/**/*

compiler:
- changed-files:
  - any-glob-to-any-file: compiler/**/*

feature:
- head-branch: ['^feature', 'feature', '^feat']

documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
