name: Pull Request CI

on:
  pull_request:
    branches: [$default-branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
        matrix:
            node-version: [22.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Using node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run lint
        run: pnpm run lint

